version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
    - POSTGRES_PASSWORD=password123
    - POSTGRES_USER=PostgresUser
    - POSTGRES_DB=fib_calc_db
    ports:
    - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports: 
    - "8080:8080"
  redis:
    image: redis:latest
    restart: always
    ports:
    - "6379:6379"
  nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev 
    ports: 
    - "80:80"
    depends_on:
    - api
    - client
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - C:\\Users\\krzysztof.janowski\\Dropbox\\Nauka_\\docker\\projects\\fibonacci_calculator_udemy_version\\api:/app
    # command: [ping 4.2.2.2]
    environment: 
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - PG_USER=PostgresUser
    - PG_HOST=postgres
    - PG_DATABASE=fib_calc_db
    - PG_PASSWORD=password123
    - PG_PORT=5432
  client: 
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    volumes:
    - /app/node_modules
    - C:\\Users\\krzysztof.janowski\\Dropbox\\Nauka_\\docker\\projects\\fibonacci_calculator_udemy_version\\client:/app
    stdin_open: true
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
    - /app/node_modules
    -  C:\\Users\\krzysztof.janowski\\Dropbox\\Nauka_\\docker\\projects\\fibonacci_calculator_udemy_version\\worker:/app
    environment: 
      - REDIS_HOST="redis"
      - REDIS_PORT=6379